### PR TITLE
adding postlude config

### PR DESCRIPTION
**Pull request by julka**
I'd like to use a postlude config (like preclude) to add text onto the end of files created through this grunt task.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by julka** [comment]
CLA signed.

**Comment by julka** [comment]
I signed the CLA last week, but the bot isn't updating that status. Is there anything I can do to move this along?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by julka** [comment]
ping?

**Pull request closed without merging**
